name: CI-Jazzy

on:
  workflow_dispatch:
  push:
    branches:
      - ros2
  pull_request:
    branches:
      - ros2

jobs:
  harmonic_ci:
    runs-on: ubuntu-22.04
    container:
      image: ros:jazzy
    strategy:
      matrix:
        ROS_REPO: [testing, main]
    steps:
      - name: Run ROS CI
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: jazzy
          import-token: ${{ secrets.GITHUB_TOKEN }}
